# Dockerfile cho frontend
FROM nginx:alpine

# Sao chép file HTML vào thư mục phục vụ của Nginx
COPY index.html /usr/share/nginx/html
COPY styles.css /usr/share/nginx/html
COPY app.js /usr/share/nginx/html