services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - app-network
    depends_on:
      - kafka
      - database

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NODE_ID: 1
    ports:
      - "9092:9092" # Broker listener
      - "9093:9093" # Controller listener
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - kafka
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid19
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "81:81"
    networks:
      - app-network
    depends_on:
      - frontend
    
networks:
  app-network:
    driver: bridge