services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: kafka:9092

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid19
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "81:81"
    depends_on:
      - frontend
