version: '3.1'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - default  # Sử dụng default network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - default  # Sử dụng default network

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid19
    ports:
      - "5432:5432"
    networks:
      - default  # Sử dụng default network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "81:81"
    networks:
      - default  # Sử dụng default network
    depends_on:
      - frontend

# Không cần khai báo app-network ở đây nữa
